module "eks-cluster" {
  source = "../eks-cluster"
  eks-cluster-name = var.eks-cluster-name
  eks-iam-role-name = var.eks-iam-role-name
  vpc_id = local.vpc_id
  tags = var.tags
  vpc-cni-version = var.vpc-cni-version
  coredns-version = var.coredns-version
  kube-proxy-version = var.kube-proxy-version
  resolve_conflicts = var.resolve_conflicts
  project = var.project
  fargate-profile-name = var.fargate-profile-name
  namespace = var.namespace
  node-group = var.node-group
  desired-size = var.desired-size
  max-size = var.max-size
  min-size = var.min-size
  max-unavailable = var.max-unavailable
  ami-type = var.ami-type
  capacity-type = var.capacity-type
  disk-size = var.disk-size
  instance-types = var.instance-types
}